### ISSUE TITLE
Frontend Traversal Finishes instantly without moving.

### ISSUE THREAD

**Issue by mtfunder** [precision-sustainable-ag/benchbot-brain-app#51]
After configuring a species map and saving, moving to the traversal tab shows the expected traversal locations of the plot. However, when start is pressed, the log immediately shows "Finished" with no attempted movement of any axis.

This feature was previously working, so some new addition has likely broken something.

I do not know what version this was happening on, but the issue was present in the software running on the BBv3 as of 4/5/2023.

Mitigating factors could be the camera was not connected (although that has not previously caused this issue).

The solution will be to determine the root cause of this bug, and to take the necessary reasonable steps to ensure we do not see it in the future.

**Comment by YazidZidane** [comment]
close as resolved
